apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cloud
  namespace: webstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        topology.kubernetes.io/region: cloud
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 238122922479.dkr.ecr.eu-west-3.amazonaws.com/k8sbackend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 25
            failureThreshold: 3
