apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webstore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cobrahzz/k8s-3tier-app.git
    targetRevision: HEAD
    path: deploy/base
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: webstore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
