grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort
    nodePort: 32000
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 10d

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
