grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort
    nodePort: 32000
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 10d
    additionalScrapeConfigs:
      - job_name: "webstore-backend"
        static_configs:
          - targets:
              - "backend.webstore.svc.cluster.local:8000"
        metrics_path: /api/health
        scheme: http

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
